openapi: 3.0.0
info:
    title: ArticlesAPI
    version: "1"

servers:
    - url: http://localhost:{port}/api/oak-test/{version}
      variables:
          version:
              default: 'v1'
          port:
              default: '8080'

paths:
  /articles:
    get:
      description: "Return all articles "
      responses:
        '200':
          description: 'Successful operation'
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/ArticlesGetAll'

  /articles/{id}:
    get:
      description: "Find article by ID"
      operationId: "getArticleById"
      parameters:
      - name: "id"
        in: "path"
        description: "ID of article to return"
        required: true
        schema:
          type: "integer"
      responses:
        '200':
          description: 'Successful operation'
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/ArticlesGetOne'
        '404':
          description: "Article not found"
        '400':
          description: "Invalid ID"





components:
    schemas:

        ArticlesGetAll:
            description: articles list structure
            type: object
            properties:
                data:
                    type: array
                    items:
                        $ref: '#/components/schemas/ArticleDto'

        ArticlesGetOne:
            description: article
            type: object
            properties:
                data:
                    $ref: '#/components/schemas/ArticleDto'

        ArticleDto:
          type: object
          properties:
            type:
              type: string
              nullable: false
            id:
              type: integer
              nullable: false
            attributes:
              type: object
              properties:
                title:
                  type: string
                  nullable: false
                body:
                  type: string
                  nullable: false
            relationship:
              $ref: '#/components/schemas/Relationship'

        Relationship:
          type: object
          properties:
            comments:
              type: object
              properties:
                data:
                  $ref: '#/components/schemas/RelationshipComments'

        RelationshipComments:
          type: array
          items:
            $ref: '#/components/schemas/CommentDto'

        CommentDto:
            type: object
            properties:
              type:
                type: string
                nullable: false
              id:
                type: integer
                nullable: false

